### ISSUE TITLE
CR1-FV copy change

### ISSUE THREAD

**Issue by MonicaLLLMMM** [iris-shanghai/VR-CNY-Village-offer#3]
Hi Mike,

帮忙把菲登扎购物村的页面上两句话去掉，谢谢：

幸运抽奖活动介绍
消费每满200欧元，有机会参与抽奖赢取价值50欧元的礼品卡

页面参考：http://bpoprod.5adian.com/cny/v5.html

**Comment by iamike** [comment]
fixed
